services:
  backend:
    image: node:14
    commands:
      - cd Backend && npm ci
      - cd Backend && npm run build
      - cd Backend && npm start
    environment:
      NODE_ENV: production
    port: 3000
